### ISSUE TITLE
record #0, bad transaction date: parsing time "3/19/2021": extra text: "21"

### ISSUE THREAD

**Issue by reiwan** [Graeme22/tastypl#3]
Fresh install, first time using this and saved the csv direct from the app (didn't open and save it after downloading it).

F0319 21:02:02.324148   18796 tastypl.go:659] record #0, bad transaction date: parsing time "3/19/2021": extra text: "21"
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc000110700, 0xc00012f110, 0x7a, 0xcb)
        C:/Users/Reiwan/go/src/github.com/golang/glog/glog.go:769 +0xbf
github.com/golang/glog.(*loggingT).output(0xce1d80, 0xc000000003, 0xc00025a070, 0xbda788, 0xa, 0x293, 0x0)
        C:/Users/Reiwan/go/src/github.com/golang/glog/glog.go:720 +0x39a
github.com/golang/glog.(*loggingT).printf(0xce1d80, 0x3, 0xb0465f, 0x24, 0xc000121bd0, 0x2, 0x2)
        C:/Users/Reiwan/go/src/github.com/golang/glog/glog.go:655 +0x153
github.com/golang/glog.Fatalf(...)
        C:/Users/Reiwan/go/src/github.com/golang/glog/glog.go:1148
main.(*portfolio).parseTransaction(0xc00007e140, 0x0, 0xc000251b00, 0x11, 0x11, 0xc000121d4e, 0xce2120)
        c:/Users/Reiwan/tastypl/tastypl.go:659 +0xf5c
main.(*portfolio).parseTransactions(0xc00007e140, 0xc000252018, 0x4d, 0x7f, 0x1000)
        c:/Users/Reiwan/tastypl/tastypl.go:564 +0xf2
main.NewPortfolio(0xc000252018, 0x4d, 0x7f, 0x0, 0x80)
        c:/Users/Reiwan/tastypl/tastypl.go:417 +0x1f0
main.main()
        c:/Users/Reiwan/tastypl/tastypl.go:1578 +0x48f
exit status 255

**Comment by Graeme22** [comment]
~~Looks like TW changed the date formatting of their CSV. Should be a quick fix.~~

Update: Not quite as easy as I thought. We can no longer use the glog parser. Take this in addition with all the other host of issues, and I think I'm going to drop support for this project. HOWEVER, don't panic! I'm working on a new implementation in Python that should do the job just fine.

**Comment by Graeme22** [comment]
If you want a temporary solution in the meantime, you can just replace all instances of `.xxxCDT`/`.xxxCST` (or other timezones) with `-0500`. Does that get it working for you?
